Add Onboarding Files
Avikaa09/froker pull request #1
Opened 2023-06-27 17:22 UTC by Avikaa09

Onboarding Portal

2023-06-29 16:43 UTC, amosaxe commented on src/pages/Restaurants/index.js
> +function Restaurants(){
Have we changed this to handle dynamic data?

2023-06-29 16:55 UTC, amosaxe requested changes
Please go through all the comments. Make sure that they are followed throughout the project.

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Offers/index.js
> +              <InputNumber />
Please add validation checks.

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Offers/index.js
> +                  <InputNumber placeholder="Max Uses" style={{ width: '50%' }} />
Have we checked responsiveness?

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Restaurants/index.js
> +function Restaurants(){
Have we changed code to handle dynamic data?

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Restaurants/index.js
> +            {/* <Statistic title="Value" value={value} /> */}
remove comments

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Subscription/Subscription.js
> +
Dont give extra lines

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Offers/index.js
> +            </Form.Item>
I dont think we have added confirmations before submission?

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Analytics/CAnalytics.js
> +import React from 'react';
change logo.svg

2023-06-29 16:55 UTC, amosaxe commented on src/components/AppRoutes/index.js
> +export default AppRoutes;
add empty line at the end of all files.

2023-06-29 16:55 UTC, amosaxe commented on src/components/Content/index.js
> +    return <div className="content">
Follow formatting

2023-06-29 16:55 UTC, amosaxe commented on src/components/AddRestaurant.js
> +
no extra lines

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Offers/index.js
> +
Add confirmations before submission(basically creating objects)

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Analytics/RAnalytics.js
> +  labels: monthlyLabels,
please have dummy data as same as expected from the backend.
Or
add code to convert the data from backend into this format

2023-06-29 16:55 UTC, amosaxe commented on src/pages/Analytics/CAnalytics.js
> +          </div>
We need customer name and other info.
Please align with ashutosh on this once. I think we want top 5 customers?

2023-06-29 16:55 UTC, amosaxe commented on src/components/Sidebar/index.css
> +.ant-menu-submenu-title {
correct the formatting

2023-06-30 08:14 UTC, Avikaa09 commented on src/components/Sidebar/index.css
> +.ant-menu-submenu-title {
done

2023-06-30 08:14 UTC, Avikaa09 commented on src/components/AddRestaurant.js
> +
done

2023-06-30 08:14 UTC, Avikaa09 commented on src/pages/Subscription/Subscription.js
> +
done

2023-06-30 08:14 UTC, Avikaa09 commented on src/pages/Restaurants/index.js
> +            {/* <Statistic title="Value" value={value} /> */}
done

2023-06-30 08:18 UTC, Avikaa09 commented on src/pages/Offers/index.js
> +              <InputNumber />
done

2023-06-30 08:19 UTC, Avikaa09 commented on src/pages/Analytics/RAnalytics.js
> +  labels: monthlyLabels,
We'll see

2023-07-27 06:01 UTC, merged